### ISSUE TITLE
Warning: Unknown prop `level` on <h1> tag

### ISSUE THREAD

**Issue by gridworkz** [codaxy/cx#42]
Hi Marko:

Just a small one. When I select `General Purpose Widgets > Heading` in CxDocs the browser gives an Unknown prop warning on the level tag. Everything seems to be fine but I can't seem to find where this is coming from. Have you seen this before? I basically get it wherever the `level` tag is used.

It's a fresh local install and I notice it doesn't happen in the online version of the docs.

Cheers,
Dave

**Comment by mstijak** [comment]
@gridworkz Thanks for reporting. I missed that one.
