### ISSUE TITLE
Disabled containers?

### ISSUE THREAD

**Issue by tymarats** [codaxy/cx#53]
Is it possible to have entire containers disabled (meaning, all form inputs on the container would be disabled)?

**Comment by mstijak** [comment]
None of the container widgets have the disabled property. 
I guess we're missing a widget which could offer that feature - FieldSet.

HTML5 fieldset elements support disabled and automatically disable inner fields.
http://www.w3schools.com/tags/tag_fieldset.asp

**Comment by mstijak** [comment]
This is now possible using the [new FieldGroup widget](https://cxjs.io/docs/widgets/field-groups).
