### ISSUE TITLE
Tooltips on mobile devices

### ISSUE THREAD

**Issue by tymarats** [codaxy/cx#57]
Tooltips look and feel a little strange on mobile devices, but they work very well on desktop. Maybe it makes sense to have some global configuration for tooltips, at least to be able to hide them all.

**Comment by mstijak** [comment]
This is now implemented. Behavior of tooltips on touch events can now be controlled using the `touchBehavior` property. Default value is `toggle`. Other allowed value is `ignore`, which makes that tooltips completely ignore touch events.

To set `ignore` behavior globally, use:
```
Tooltip.prototype.touchBehavior = 'ignore';
```

**Comment by tymarats** [comment]
Add this in the docs?
