### ISSUE TITLE
TextBox autocapitalize

### ISSUE THREAD

**Issue by tymarats** [codaxy/cx#79]
Enable flags for autocapitalization, autocorrection, autocompletion for TextBox on mobile devices, as described here: https://davidwalsh.name/disable-autocorrect. 

Usage case: username input, which should never be autocapitalized.

**Comment by mstijak** [comment]
This is now supported by using `inputAttrs`:

```
<TextField value:bind="name" inputAttrs={{ autoComplete: "off" }} />
```
