### ISSUE TITLE
Implement toggle mod for Grid with multiple selection

### ISSUE THREAD

**Issue by sasatatar** [codaxy/cx#88]
When passing multiple='true' attribute to the Grid widget, it is possible to select multiple rows holding the Ctrl key. Default behavior deselects all other rows if Ctrl key is not down. 

Toggle mod would allow multiple rows selection without holding down the Ctrl key.

**Comment by mstijak** [comment]
It's now possible to set toggle option inside the selection config object which enables desired behavior.

```
selection={{ type: KeySelection, bind: 'selection', multiple: true, toggle: true }}
```
